matrix:
  include: 
  - os: osx
    language: objective-c
    osx_image: xcode11.3
    script:
      - swift package generate-xcodeproj
      - xcodebuild test -scheme Hippolyte-Package -destination platform="macOS" -enableCodeCoverage YES
    after_success:
      - bash <(curl -s https://codecov.io/bash) -J 'Hippolyte'